name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build-libraries:
    runs-on: windows-2019
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: '2022.04'
      - uses: actions/checkout@v2
      - uses: chetan/git-restore-mtime-action@v1
      - name: Update DLL
        run: |
          zef install --/test LibraryMake
          zef install --/test LibraryMake
          zef install --/test LibraryMake
          raku Build.pm6 --rebuild
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Windows DLL save
          file_pattern: resources/libraries/pdf.dll
  raku:
    needs: build-libraries
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-2019
#          - windows-latest
        raku-version:
          - 'latest'
          - '2022.02'
        exclude:
          - os: windows-latest
            raku-version: 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Dependencies
        run: |
          zef install --/test LibraryMake
          zef install --/test App::Prove6
          zef install --deps-only .
          zef build .
      - name: Install Prerequisite Libraries (MacOS)
        if: matrix.os == 'macOS-latest'
        run: brew install openssl
      - name: Run Tests
        run: |
          prove6 -I. t
          # also verify compatibility with last PDF version
          zef install .
          zef --verbose install PDF
