name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build-libraries:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: '2022.04'
      - uses: actions/checkout@v2
      - uses: chetan/git-restore-mtime-action@v1
      - name: Setup Build Environment
        run: |
          choco install make
          choco install mingw
          refreshenv
      - name: Update DLL
        run: |
          zef install --/test LibraryMake
          raku Build.pm6 --rebuild
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Windows DLL save
          file_pattern: resources/libraries/pdf.dll
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        raku-version:
          - 'latest'
          - '2021.12'
        exclude:
          - os: windows-latest
            raku-version: 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Dependencies
        run: |
          zef install --/test LibraryMake
          zef install --/test App::Prove6
          zef install --deps-only .
          zef build .
      - name: Run Tests
        run: |
          prove6 -I. t
          # also verify compatibility with last PDF version
          zef install .
          zef --verbose install PDF
